channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.10.5=py39haa95532_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - colorama=0.4.6=py39haa95532_0
  - contourpy=1.3.0=py39h2b77a98_2
  - cudatoolkit=11.3.1=h59b6b97_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - expat=2.7.3=h9214b88_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39h5769e4c_0
  - freetype=2.14.1=h57928b3_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.2.4=py39hdb6649d_0
  - icu=75.1=he0c23c2_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=haa95532_1164
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libboost=1.86.0=h444863b_2
  - libboost-python=1.86.0=py39h8f1c5a3_3
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_14
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h8ee18e1_14
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libpng=1.6.51=h7351971_0
  - libpq=17.7=h7c87ebf_1
  - librdkit=2025.03.5=h0cb3073_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=20.1.8=h29ce207_0
  - matplotlib-base=3.9.4=py39h5376392_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py39h0b37514_0
  - mkl_fft=1.3.11=py39h5810407_1
  - mkl_random=1.3.0=py39ha5e6156_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=2.0.2=py39h12f7302_2
  - numpy-base=2.0.2=py39he4e2855_2
  - openbabel=3.1.1=py39h6bddc37_9
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h743b7ac_0
  - pcre2=10.44=h99c9b8b_2
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pycairo=1.28.0=py39h2b67685_0
  - pyparsing=3.2.3=pyhe01879c_2
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - rdkit=2025.03.5=py39hfb65f61_0
  - reportlab=4.4.1=py39ha55e580_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - setuptools=72.1.0=py39haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.43=py39h0802e32_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tqdm=4.67.1=py39h9909e9c_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h1b5488d_5
  - pip:
      - filelock==3.19.1
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
